changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionFormat: '## {{ .Version }}'
changelogPath: CHANGELOG.md
versionExt: md
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
footerFormat: |
  #### Affects
  {{- range (customs .Changes "Affects" | uniq) }}

  - {{.}}
  {{- end }}
kinds:
  - label: Added
    key: added
    auto: minor
  - label: Breaking
    key: breaking
    auto: major
  - label: Changed
    key: changed
    auto: major
  - label: Deprecated
    key: deprecated
    auto: minor
  - label: Removed
    key: removed
    auto: minor
  - label: Fixed
    key: fixed
    auto: patch
  - label: Security
    key: security
    auto: patch
custom:
  - key: Affects
    label: Affects
    type: enum
    enumOptions:
      - user
      - operator
      - developer
